version: "3"
services:
  app:
    image: front_end
    restart: always
    build: .
    ports:
      - 80:80
    depends_on:
      - nginx
  nginx:
    container_name: nginx
    image: nginx
    restart: always